boostcampwm-2022/web32-bmNotion

client/package-lock.json, client/package.json, client/src/App.tsx, client/src/pages/Login.tsx
feat/5 -> dev
로그인 페이지 레이아웃 생성
라우팅 적용
close #5
=>  feat: 로그인페이지 레이아웃 구현 & 라우팅 적용

client/src/pages/Register.tsx
- feature/13 -> dev
- 회원가입 페이지 닉네임, ID, password validation 함수 추가
=> [feat] FE. 닉네임, ID, password validation 함수 추가

server/package-lock.json, server/package.json, server/src/db/db.crud.js, server/src/db/db.server.js, server/src/index.js, server/src/main/main.cotroller.js
-[x] 기능 추가
-[ ] 기능 삭제
-[ ] 버그 수정
-[ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
feature/6 -> dev
MongoDB 연결 함수를 추가하였습니다.
=> BE. 데이터 베이스 연결 및 초기화

server/src/db/db.crud.js
=> [BE] feat: DB CRUD 작업

server/src/auth/auth.controller.js, server/src/auth/auth.router.js, server/src/auth/auth.service.js, server/src/db.config.json
feature/18 -> dev
auth 기능 구현함.
=> [BE] auth 로직 구현

client/src/App.tsx, client/src/pages/Login.tsx, client/src/pages/Register.tsx
feature/12 -> dev
로그인 페이지 API 요청 && 실패 메시지 출력
페이지 url 변경 & 회원가입페이지 form key값 변경
=> Feature/12 로그인 페이지 API 요청 && 실패 메시지

client/src/pages/Register.tsx
feature/29 -> dev
API Form에 이미지 제대로 전송되도록 코드 수정
회원가입 실패시 원인 메시지 받아서 오류 메시지로 출력
=> Feature/29 회원가입 API form으로 이미지까지 전송 & 회원가입 실패시 원인 메세지 출력

server/src/page/page.controller.js, server/src/page/page.router.js, server/src/page/page.service.js
- feature/44 -> dev
빈 페이지를 생성하여 DB에 저장하는 API를 구현했습니다.
=> feat: 페이지 생성 API 구현

server/src/auth/auth.service.js, server/src/db.config.json
회원 가입 시 workspace 자동 생성
- feature/54 -> dev
- 회원가입 시, 사용자 개인 워크스페이스 자동생성 기능을 추가하였습니다.
=> [BE] 회원가입 시 workspace 자동 생성

server/src/page/page.controller.js, server/src/page/page.router.js, server/src/page/page.service.js
- feature/45 -> dev
클라이언트에서 요청하는 페이지의 정보를 전송하는 API 구현
resolves:#45
=> feat: page 로딩 API 구현

client/src/App.tsx, client/src/pages/Login.tsx, server/src/auth/auth.controller.js, server/src/auth/auth.service.js, server/src/page/page.service.js
- feature/61-> dev
로그인 후 라우팅에 필요한 pageid를 전송하고 pageid로 라우팅하는 것을 구현
resolves: #61
=> [#61] feat: 로그인 후 라우팅 구현

client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx, client/src/pages/MainPage.tsx, server/src/auth/auth.service.js
- feature/67 -> dev
- 블록에서 shift + enter 입력시 block이 늘어나지 않던 버그 수정
=> [#67] fix: block에서 shift+enter시 block 안늘어나는 버그 수정

client/src/components/BlockContent.tsx
- feature/67 -> dev
- block 모달창이 block 위에 생성되는 버그 수정
=> [#67] Feat: block 모달창이 block 위에 생성되는 버그 수정

client/src/components/BlockContent.tsx, client/src/components/modal/BlockModalContent.tsx, client/src/components/modal/BlockModalContentType.tsx
- feature/71 -> dev
- 블록 모달창 내 리스트 항목들을 컴포넌트화 한다.
=> [#71] Refactor:  블록 모달창의 타입 리스트 항목 컴포넌트화

client/src/pages/Login.tsx, client/src/pages/Register.tsx, server/src/index.js, server/src/main/main.cotroller.js, server/src/main/main.router.js
- feature/68 -> dev
URL에 직접 접근할 때 index.html에 접근할 수 있도록 설정
resolves: #68
=> [#68] feat: URL 직접 접근 라우팅 구현

client/package.json, client/webpack.dev.js
- feat/login -> dev
dev 서버에서 새로고침이 작동하지 않는 현상 수정
fixes:#75
=> [#75]feat: dev서버 새로고침 수정

client/src/components/BlockContent.tsx
- feature/66 -> dev
- Block의 type이 변경될 때 style도 같이 변경되도록 수정하였습니다.
=> [#66] Feat: type에 따른 Block 스타일 변경

client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx
블록 생성 & 수정시 blockId로 포커스를 부여하는 함수 호출
- [ x] 기능 추가
- feature/79 -> dev
블록 생성 & 수정 시 포커스를 부여한다.
=> [#79] feat: 블록 생성 & 수정시 포커스 부여

client/src/components/BlockContent.tsx, client/src/components/modal/BlockModalContent.tsx, client/src/components/modal/BlockModalContentType.tsx
- feature/78 -> dev
- block 모달창 타입 항목 클릭시 스타일 변경
- handleType 함수 추가
=> [#78] Feat: block 모달창 타입 항목 클릭시 스타일 변경

server/package-lock.json, server/package.json, server/src/index.js, server/src/workspace/workspace.controller.js, server/src/workspace/workspace.router.js
- feature/88-> dev
workspace 개별 작업 전 공통 설정
=> [#88] Feat: workspace api router, controller 초기 설정

client/package-lock.json, client/package.json, client/webpack.config.js, client/webpack.dev.js
- feature/93-> dev
dev server hot 리로드 설정
fixes: #93
=> [#93] Feat: dev server hot 리로드 설정

client/src/components/modal/SettingModalContent.tsx, client/src/pages/MainPage.tsx, server/src/auth/auth.controller.js, server/src/index.js, server/src/response.message.json, server/src/user/user.controller.js, server/src/user/user.router.js, server/src/user/user.service.js, server/src/utils/response.util.js, server/src/workspace/workspace.controller.js, server/src/workspace/workspace.service.js
- feature/92 -> dev
워크스페이스 설정 모달창을 출력하고 사용자를 검색하고 초대할 수 있는 기능을 추가했습니다.
=> [#92,#90] Feat: 사용자 검색 및 초대 구현

client/package-lock.json, client/package.json, client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx
=> [WIP] [#85] Feat: block 드래그 앤 드롭 구현

client/package-lock.json, client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx
- feature/96 -> dev
- 위 아래 방향키 입력시 block간 이동 구현
- shift Enter 입력으로 한 block에 여러 line이 존재할 경우 버그 발생
=> [WIP] [#96] Feat: 방향키 입력시 block간 이동 구현

client/src/components/BlockContent.tsx
- 변수명 type => toType으로 수정
- ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다.
=> fix: 변수명 toType 으로 교체

client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx
- feature/85 -> dev
- 드래그앤 드롭시 내용 유지 안되는 버그 수정
=> [#85] fix: 드래그앤 드롭시 내용 유지 안되는 버그 수정

client/src/pages/MainPage.tsx, server/src/index.js, server/src/page/page.controller.js, server/src/page/page.router.js, server/src/page/page.service.js, server/src/workspace/workspace.controller.js, server/src/workspace/workspace.service.js
- feature/104 -> dev
- 페이지 리스트 ui 정상작동 확인
=> Feat: page list ui

client/src/components/BlockContent.tsx
e.target.textContent = 유지할 값 으로 로직 구현
- [x 버그 수정
- feature/87 -> dev
- e.target.textContent = 텍스트값 으로 구현
=> bug: 타입 변경시 text 올바른 수정

client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx, client/src/pages/MainPage.tsx
- feature/117 -> dev
- title 생성 및 input 이벤트 처리
- title에서 Enter 키 입력 이벤트 처리
=> [#117] Feat: Page의 title 생성 및 이벤트 처리

client/src/components/PageComponent.tsx
- feat/login -> dev
- ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
- ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다.
=> [Bug] 엔터 판별시 e.code에서 e.key로 변경

client/src/components/PageComponent.tsx, server/src/workspace/workspace.controller.js, server/src/workspace/workspace.service.js
- feature/118 -> dev
- workspace api 추가하였습니다.
=> [#118] Feat: workspace add api 

client/src/components/PageComponent.tsx, client/src/config/config.js, client/src/utils/axios.request.ts, server/src/page/page.service.js
- feature/123 -> dev
- 페이지 로드,동기화 및 페이지 정보 전송 구현
=> [#123, #124] Feat:  페이지 로드,동기화 및 페이지 정보 전송 

server/src/page/page.controller.js, server/src/utils/response.util.js
- feat/login -> dev
페이지 저장 로직에 매개변수 순서가 잘못되어 수정
=> [#132] Feat: page 저장 버그 수정

client/src/components/PageComponent.tsx, client/src/components/modal/SettingModalContent.tsx, client/src/config/config.js, client/src/pages/Login.tsx, client/src/pages/MainPage.tsx, client/src/pages/Register.tsx, client/src/utils/axios.request.ts, server/src/auth/auth.service.js, server/src/user/user.service.js
- feat/login -> dev
axios 요청 관련 부분 리팩토링
=> [#134] Refactor: axios 요청 리팩토링

client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx
- feature/144 -> dev
- block간 이동시 caret 위치 유지
- 여러 줄인 블록에 대해서도 정상 동작
=> [#144] Fix: 키보드 위 아래 입력에 대한 블록 이동 버그 수정

client/src/components/PageComponent.tsx, server/src/page/page.service.js
- feature/149 -> dev
- title 기본값 변경
- title 기본 스타일 변경
=>   [#149] Refactor: title 기본값 및 기본 스타일 변경

client/src/components/BlockContent.tsx
- fix/151 -> dev
- 잘못 삭제된 onKeyDown 내 handleOnBackSpace 복구
=> [#151] fix: 잘못삭제된 백스페이스 핸들 코드 복구

client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx
- feature/144 -> dev
- Sift+Enter 직후에 위로 이동시 발생하는 버그 수정
=> [#144] Fix: 여러줄인 block에 대한 동작 버그 수정

client/src/components/PageList.tsx, client/src/components/WorkspaceList.tsx
- feature/155 -> dev
리스트 리렌더 버그 수정
=> [#155] Fix: 수정 리스트 리렌더 버그

client/src/components/BlockContent.tsx, client/src/components/modal/BlockOptionModalContent.tsx
- feature/158 -> dev
- 옵션 버튼의 모달창을 이용한 블록 삭제 기능을 추가했습니다.
=> [#158] Feat: 옵션 버튼 모달창을 이용한 블록 삭제 기능

client/src/components/BlockContent.tsx, client/src/components/PageComponent.tsx, client/src/components/WorkspaceList.tsx, client/src/components/block/BlockContent.tsx, client/src/components/block/StyledBlockContent.tsx, client/src/pages/MainPage.tsx
- feature/157 -> dev
- feature/160 -> dev
- 블록 이동 함수를 리팩토링 했습니다.
- 블록 스타일 관련 컴포넌트를 리팩토링 했습니다.
=> [#157, #160] Refactor: 블록 관련 컴포넌트 리팩토링

client/src/components/PageComponent.tsx
- bug/170 -> dev
- 제목에서 Enter 입력시, isComposing모드를 핸들링하지 않아 생기는 버그 수정
=> [#170] bug 제목에서 Enter입력시 isComposing 모드핸들링

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx, client/src/components/block/StyledBlockContent.tsx, server/package-lock.json, server/package.json, server/src/db/db.crud.js, server/src/index.js, server/src/main/main.router.js, server/src/page/page.controller.js, server/src/page/page.service.js, server/src/sse/sse.connect.js, server/src/workspace/workspace.service.js
- feature/172 -> dev
실시간 편집 구현
=> [#172] Feat: 실시간 편집 구현

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx, client/src/components/block/StyledBlockContent.tsx, client/src/components/modal/BlockModalContent.tsx, client/src/components/modal/BlockModalContentType.tsx, client/src/components/modal/BlockOptionModalContent.tsx, client/src/components/modal/TypeChangeModalContent.tsx, client/src/components/modal/TypeChangeModalContentType.tsx, client/src/pages/MainPage.tsx
- feature/179-> dev
드래그로 블록 다중 선택 및 다중 블록에 대한 이벤트 구현
=> [#179] Feat: 드래그로 블록 다중 선택 및 다중 블록에 대한 이벤트 구현

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx, client/src/components/block/StyledBlockContent.tsx
=> [WIP] [#177] 에디터 Enter, Back space에 대한 동작 수정 

client/src/components/block/BlockContent.tsx
- feat/177 -> dev
- UL, OL 타입에서 beforeContent를 활용해서 스타일링 부여
=> [#177] feat: UL, OL beforeContent로 스타일링

client/package-lock.json, client/package.json, client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx, client/src/components/block/StyledBlockContent.tsx, client/src/components/modal/BlockModalContent.tsx, client/src/components/modal/BlockModalContentType.tsx, client/src/components/modal/BlockOptionModalContent.tsx, client/src/components/modal/TypeChangeModalContent.tsx, client/src/components/modal/TypeChangeModalContentType.tsx, client/src/config/config.js
- feature/194 -> dev
고유한 블럭을 식별하기 위해 blockId를 number에서 uuid로 변경
=> [#194] feat: blockId uuid 적용

client/src/components/PageComponent.tsx
- feature/183 -> dev
- 제목에서 Enter 입력시 caret이 올바르게 이동하지 못하는 버그 수정
=> [#183] 에디터 Enter, Back space에 대한 동작 수정

client/src/components/PageComponent.tsx
- feature/183 -> dev
- block이 없을 경우 제목에서 Enter 입력시 이동 안되는 버그 수정
=> [#183] Fix: 에디터 Enter, Back space에 대한 동작 수정 

client/src/components/PageList.tsx, client/src/components/WorkspaceList.tsx, client/src/components/modal/SettingModalContent.tsx, client/src/components/modal/TopBarModalContent.tsx, client/src/pages/MainPage.tsx
- feature/202 -> dev
- Setting 모달 스타일 변경
- topbar 버튼 조정, 모달 스타일 변경
=> [#202] Design: Setting 모달 스타일 변경

client/src/components/PageComponent.tsx
- feature/203 -> dev
key값으로 uuid를 재생성하여 부여해서 리렌더링이 계속 발생하던 현상을 blockId 값으로 바꿔 수정
=> [#203] Fix: 카렛 이동 버그 수정

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx
- feature/212 -> dev
- caret 이동 함수 변경
- 제목과 처음 block간의 방향키 입력에 대한 상호작용 추가
- 처음 block에서 Backspace 입력시 제목과 병합되는 기능 추가
=> [#212] FIX, Feat: 제목과 첫번째 block의 상호작용

client/package-lock.json, client/package.json, client/webpack.config.js
- feature/216 -> dev
assets 빌드시 복사
=> [#216] Chore: webpack assets copy setting

client/src/components/PageComponent.tsx, client/src/components/PageList.tsx, client/src/components/WorkspaceList.tsx, client/src/components/block/BlockContent.tsx, client/src/components/modal/BlockOptionModalContent.tsx, client/src/components/modal/SettingModalContent.tsx, client/src/components/modal/TypeChangeModalContentType.tsx, client/src/pages/MainPage.tsx, client/src/utils/axios.request.ts, server/src/index.js, server/src/sse/sse.connect.js
- feature/221 -> dev
배포 전 콘솔 출력문 제거
=> [#221] Refactor: 콘솔 출력 제거

client/src/components/PageComponent.tsx, client/src/config/config.js, client/src/pages/MainPage.tsx, server/src/page/page.service.js, server/src/workspace/workspace.controller.js, server/src/workspace/workspace.router.js, server/src/workspace/workspace.service.js
- feature/223 -> dev
새로고침 또는 pageid로 직접 url 접근했을 때 API 요청하여 워크스페이스 정보 받아오는 처리
resolves: #223
=> [#223] !Hotfix: 새로고침 정상 동작 처리

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx
- feature/231 -> dev
-  text입력시 caret 변경 코드 추가
=> [WIP][#231] Fix: 다른 사람이 page 수정시 caret이 초기화되는 bug 수정

client/src/components/modal/SettingModalContent.tsx
- feature/230 -> dev
- 설정 모달의 사용자 초대 리스트 UI 변경
=> [#230] design: 설정 모달의 사용자 초대 리스트 UI 변경

client/src/components/PageComponent.tsx
- feature/234 -> dev
- caretPosition을 state에서 variable로 변경.
=> [#234] Refactor: caretPosition state에서 variable로 변경

client/src/components/block/BlockContent.tsx
- hotfixes/241
- handleOnKeydown에서 드래드 상태 && Enter || Space || BackSpace이면 기본동작을 막는다.
resolve: #241
=> [#241] hotfixes: 드래그 상태에서 핸들링 아직 못하는 동작들 방지

client/src/components/PageComponent.tsx, client/src/components/PageList.tsx, client/src/components/WorkspaceList.tsx, client/src/config/config.js, client/src/pages/MainPage.tsx, server/src/page/page.service.js, server/src/workspace/workspace.service.js
- feature/238 -> dev
워크스페이스 리스트와 페이지 리스트에서 항목 추가시 리스트를 다시 불러오지 않고 바로 state에 추가하여 반응성 향상 및 API 요청 횟수 감소
=> [#238] Refactor: 사이드바 리스트 리팩토링

client/src/components/block/BlockContent.tsx, client/src/config/config.js, client/src/pages/MainPage.tsx, server/src/user/user.controller.js
- feature/245 -> dev
프로필 이미지 출력 안 되는 버그 수정
=> [#245] Fix: 프로필 이미지 출력 안 되는 버그 수정

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx
=> [#231] Fix: 다른 사람이 page 수정시 caret 초기화 됨

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx, client/src/components/block/StyledBlockContent.tsx
- feature/251 -> dev
- 드래그앤 드롭시 블록 색깔 및 글씨 투명도 변경
=> [#251] Design: 드래그앤 드롭 스타일 변경

client/src/components/block/BlockContent.tsx
- feature/232 -> dev
- modal 제어 버튼 클릭시 caret null처리
=> [#232] Feat: 마우스 이벤트로 블럭 생성 및 수정 시 caret null 처리 

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx
=> [#255] [FE] keyDown 이벤트에서 isComposing 모드시 시그널 무시

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx, client/src/components/block/StyledBlockContent.tsx, client/src/components/modal/BlockModalContent.tsx, client/src/components/modal/BlockModalContentType.tsx, client/src/components/modal/BlockOptionModalContent.tsx, client/src/components/modal/TypeChangeModalContent.tsx, client/src/components/modal/TypeChangeModalContentType.tsx, client/src/types/block.d.ts
- style/258 -> dev
- 여러번 쓰이는 interface 별도 파일로 분리
=> [#258] style: 여러번 쓰이는 interface 별도 파일로 분리

client/src/components/block/BlockContent.tsx, client/src/pages/MainPage.tsx
- feature/260 -> dev
- 드래그시 offsetTop null 버그 발생 수정
=> [#260] Fix: 드래그시 offsetTop null 버그 수정

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx
- hotfixes/226 -> main
- textContent에 대해 null guard 추가
- childNodes에 대해 null guard 추가
=> [#226] !Hotfix: null 오류 처리

client/src/pages/MainPage.tsx
- feature/264 -> dev
- 드래그 컴포넌트 안에 박스가 포함될 경우 select 안되는 버그 수정
=> [#264] fix: 드래그 컴포넌트의 블록 선택 조건 수정

client/src/components/PageComponent.tsx, server/src/db/db.crud.js, server/src/index.js, server/src/page/page.controller.js, server/src/page/page.service.js, server/src/sse/sse.connect.js
- feature/196-> dev
페이지 변경 사항 DB 반영 주기 변경
=> [#196] Feat: DB 연결 횟수 및 sse disconnect 설정

server/src/db/db.crud.js, server/src/index.js, server/src/main/main.router.js, server/src/page/page.controller.js, server/src/page/page.service.js, server/src/workspace/workspace.service.js
문서 수정 정보가 누락되는 현상으로 로직 롤백
- feature/196 -> dev
변경사항 롤백
=> [#196] fix: 블록 편집 로직 롤백

client/src/components/modal/BlockModalContent.tsx, client/src/components/modal/TypeChangeModalContent.tsx, client/src/pages/MainPage.tsx
- feature/278 -> dev
- 블록 +모달에 고유 key 추가 
- 블록 옵션 모달에 고유 key 추가
=> [#278] fix: 블록 모달에 고유 key 추가

client/src/components/PageComponent.tsx, client/src/components/block/BlockContent.tsx, server/src/sse/sse.connect.js, server/src/workspace/workspace.service.js
- feature/279 -> dev
새로고침 시 워크스페이스 제목에 id가 표시되는 현상 수정
sse connection이 여러 번 일어나는 현상 수정
=> [#279, #280] 새로고침, SSE 연결 버그 수정

client/src/components/block/BlockContent.tsx
=> [#284] FE OL의 beforeContent 삭제
